version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-bookmark-app"
s3_bucket = "labstack-499dbaf3-42b8-489c-9d64-187-samserverless-vp4aixbxdrjk"
s3_prefix = "sam-app"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StackName=\"\" APIGatewayStageName=\"dev\" LambdaDeploymentRole=\"arn:aws:iam::797885183738:role/LambdaDeploymentRole\" StepFunctionsDeploymentRole=\"arn:aws:iam::797885183738:role/EventBridgeStateMachineRole\""