/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "<AWS_REGION>",
    "aws_content_delivery_bucket_region": "<AWS_REGION>",
    "aws_cognito_identity_pool_id": "<pool_id>",
    "aws_cognito_region": "<AWS_REGION>",
    "aws_user_pools_id": "<pool_id>",
    "aws_user_pools_web_client_id": "<app_id>",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "Bookmarking App",
            "endpoint": "https://<apigwID>.execute-api.<AWS_REGION>.amazonaws.com/dev",
            "region": "<AWS_REGION>"
        }
    ]
};
export default awsmobile;